export {
  getAccessToken,
  clearTokenCache,
  BtgAuthError,
  type TokenResponse,
} from "./btgApiAuth.js";

export {
  buildHeaders,
  handleResponse,
  BtgApiError,
  type BtgError,
  type ErrorMetadata,
  type ResponseError,
} from "./btgApiUtils.js";

export type {
  PositionDateRequest,
  PositionPURequest,
  PositionPeriodFilter,
  FixedIncomeHistoryRequest,
  ACCACE,
  AccountingGroup,
  Acquisition,
  Prices,
  Acquisitions,
  ValuesPerCurrency,
  ValuesPerCurrencySBCLC,
  ValuesPerCurrencyACC,
  ACCs,
  AveragePrice,
  BMFFuturePosition,
  BMFOptionPosition,
  CashCollateral,
  CashInvestedName,
  CashInvested,
  CetipOptionPosition,
  CollateralPositions,
  Commitments,
  Credit,
  CryptoAsset,
  CryptoAcquisition,
  CurrentAccount,
  DebtEarlyTerminationPeriod,
  DebtEarlyTerminationSchedules,
  Derivative1,
  Equities1,
  FixedIncome1,
  ReferenceAsset,
  ForwardPositions,
  Fund,
  InvestmentFund1,
  IrAliquots,
  Loan,
  NDFPosition,
  TickerInfo,
  OptionPositions,
  Others,
  Pension,
  Positions,
  PrecatoryAsset,
  PrecatoryAcquisition,
  PrecatoryScenario,
  PortfolioInvestments,
  RealEstate,
  Receivables,
  SBCLC,
  StockLendingPositions,
  StockPositions,
  StructuredProducts,
  SwapPosition,
  SummaryAccount,
  InvestmentFund,
  InvestmentFundCotaCetipada,
  FixedIncome,
  Credits,
  PensionInformations,
  Commodity,
  Equities,
  Derivative,
  FixedIncomeStructuredNote,
  PayableReceivables,
  PendingSettlements,
  CryptoCoins,
  Cash,
  CashCollateralRoot,
  Precatories,
  PrecatoriesCR,
  Position,
  PositionData,
  PositionDownloadData,
} from "./btgApiPositionTypes.js";

export {
  getPositionByAccount,
  getPositionByAccountAndDate,
  getPositionUnitPriceByAccount,
  getPositionUnitPriceHistoryByAccount,
  getPartnerPosition,
  getPositionRefresh,
  getPositionUnitPriceByAccountV2,
  getPositionUnitPriceHistoryByAccountV2,
  getPositionUnitPriceHistoryByPartnerV2,
  getPositionUnitPriceHistoryByAccountsV2,
} from "./btgApiPosition.js";

export {
  type OperationHistoryPartnerRequest,
  getMovementsByAccountFull,
  getMovementsByAccountMonthly,
  getMovementsByAccountWeekly,
  getMovementsByPartnerAndPeriod,
  getMovementsByPartnerMonthly,
  getMovementsByPartnerWeekly,
} from "./btgApiOperation.js";
